### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by cmrd-senya** [diaspora/api-documentation#10]
Current API spec doesn't have error handling specification.

In a chat at the IRC channel @denschub expressed his opinion that API error responses body should have the following form:
```json
{"code": "[status code]", "message": "[english description]"}
```

HTTP status code matches the `"code"` field in the JSON reply.

In this issue we can discuss the technical details on the error handling in the API to decide how exactly to specify them.

Later I'll try to make a list of possible errors and corresponding status codes.

**Comment by frankrousseau** [comment]
The format seems good to me. The question is how precise we want to be. Generalistic errors are less descriptive but will lead to simpler code. On the opposite, per-controller based error messages are more precise but make the implementation more cumbersome.

**Comment by skyschub** [comment]
Shame on me for not responding here.

> The question is how precise we want to be.

Good question. In my opinion, Rails is actually doing a pretty good job here. If, for example, a validation fails, it returns HTTP 422, but puts a lot of details in the actual error message. Something might be possible for the API as well: a client would know that there was an error with the entity submitted, and it can display the error message if it wants to. Is there any reason not to behave like this?

**Comment by frankrousseau** [comment]
It will make the code simpler. Putting descriptive error message will probably leads to a more complicated code, will make the current API PR bigger and will take time.  
Rails has an automatic scheme to generate error messages but what is described in this issue looks more like business logic messages. It will require to put different messages for each controller and find consensus for each of them.

Descriptive error messages may sound good. But people are waiting for an API and don't care (yet) about error codes. From my experience of software projects, it seems more reasonable to start with an API that returns generalistic error messages. Once people will start using it, we'll have feedback and more motivation to implement detailed error messages. Others will be able to contribute. In the current situation, the have to wait we do the work on the currently opened PR. Adding error messages could be an easy way to start for new contributors.

After writing this, I feel like the first question to answer is when do we implement the specific error handling.

**Comment by skyschub** [comment]
> Putting descriptive error message will probably leads to a more complicated code

I'm not sure. Rails returns these validation messages in any case, I don't see how it could make the code more complicated? In fact, returning a generic validation message seems more complicated, as we'd actually have to write them, instead of just returning what AR gives us? But maybe I'm missing something.

**Comment by frankrousseau** [comment]
Generic messages are [already implemented](https://github.com/diaspora/diaspora/pull/7462/files#diff-5fc9f20656663e889401175d1de05652R10). It may require a few tweaks to match this issue but the code is almost done. By catching we have a kind of generic error handling. 

But what I understood from this issue is that description is that we want clean messages that explain properly what is happening. It will require including a lot of try / catch inside the code and add many texts to locales.

**Comment by skyschub** [comment]
Well, we seem to have a different definition of "generic", I guess. In the code you linked, you, in fact, already pass the ActiveRecord validation messages through:

https://github.com/frankrousseau/diaspora/blob/0676ffd18822d212fc23b042bf892060df65c9a8/app/controllers/api/v1/base_controller.rb#L21-L24

Which basically is exactly what I was proposing. :) I don't see the reason for writing per-model customized messages, just yet. With that, I agree with you: if it turns out it becomes an issue, we can always implement them. But for now, I wouldn't.

**Comment by frankrousseau** [comment]
Ok great! And sorry for the misunderstanding. I will look soon to adapt the base controller code to match this issue. I'll ping you for a review when it's done.

**Comment by HankG** [comment]
Should this be closed?  It seems that the documentation has this in it already.

**Comment by skyschub** [comment]
> Should this be closed? It seems that the documentation has this in it already.

In addition to the general documentation about errors, each endpoint probably should describe possible error conditions.

**Comment by skyschub** [comment]
On a second thought, let's track those in individual issues.
