### ISSUE TITLE
Unlike error inconsistency with underlying service call

### ISSUE THREAD

**Issue by HankG** [diaspora/api-documentation#15]
The current Likes specification on an unlike request on a post which the user didn't already like is for it to throw a 404 error with the message "Like doesn’t exist".  The underlying LikesService however doesn't throw an error of any kind.  It is coded to return fine if this happens.  Without doing some likes math before/after the call I can't fit this spec without changing the underlying LikesController.  Since the net effect at the end of the call is to have the like not set either way I'm inclined to change the spec to get rid of this error mode.  Thoughts?

**Comment by skyschub** [comment]
I tend to say to not get rid of the error. You are right, the outcome is probable the same - just as with trying to like a thing that's already liked, but to me, it feels like the application should know if it tries to unlike something that wasn't liked in the first place. Such an action would indicate some kind of state inconsistencies inside the app, at which point the app might consider validating or flushing caches. Since in an ideal future(tm), the API interactions would be the only code in the backend, I feel we shouldn't make arguments based on "the current behavior is X, and implementing it that way would be simpler". Opinions? :)

**Comment by HankG** [comment]
I agree I  feel better about it throwing an error if it tries to do something that it shouldn't do.  The question would be if I make a change to the lower level Likes Service, which currently doesn't error in any way in this condition, or to the API implementation where it does some additional checks afterward to see if it had an effect or not.  The additional checks at the API layer was what I did on the comments API endpoint to check that the post is associated with the comment as the caller thought it was.

**Comment by skyschub** [comment]
In this case, I'd probably tough the service itself. There is no harm throwing an exception in the current frontend - this is something that shouldn't really happen anyway. Unless someone disagrees, I'd go with that. In any case, that's probably an issue we should be discussing in the main project, not here. That is, if there is something to discuss, touching the service feels pretty uncontroversial here.

And since we've resolved this discussion here... begone, issue!
