### ISSUE TITLE
Lower level comments service doesn't use post ID except on create

### ISSUE THREAD

**Issue by HankG** [diaspora/api-documentation#21]
In the current API spec when doing anything specifies the post ID and the comment ID (except on create).  The lower-level CommentService only uses the comment ID.  This manifests as the post ID is part of the REST endpoint string but is not used.  Should the endpoint be made consistent with the actual behavior, therefore (for example):

This:
`DELETE /api/v1/posts/:post_guid/comments/:comment_guid`

Becomes:
`DELETE /api/v1/comments/:comment_guid`

Since comments are only on posts I see how we got to the current design, and if we turn it around then we'd have to change the POST create endpoint in a way that would make it inconsistent with how things like Likes work.  If we keep this as is then we have to take out some of the failure modes in the documentation since it will never fail on an incorrect post GUID, unless we want to add those checks explicitly in ways that aren't coded up in CommentService.  I could envision querying for the post then querying that the comment is on the post if we decide it is important to make sure that the comment is properly associated with the post as the caller intended.

So the three potential paths forward I see are:

1. Leave it as is and don't worry about the posts ID not being used
2. Leave it as is and document this behavior about the posts ID
3. Change the endpoint definition to something like the above example
4. Write an association check in the API implementation which confirms that the comment is meant for the post that the user input

**Comment by HankG** [comment]
The more I think about it though the more important it is to have that extra consistency check in the API so I'm inclined to add it in even though the underlying service doesn't use it because at least through the UI it's difficult to get the wrong comment ID. However if that is the case do we want to have another error report saying that the Comment isn't associated with the requested post or just reuse the permissions one?

**Comment by skyschub** [comment]
I agree with your last comment, but for a different reason. Working with comments on the root level somewhat assumes we only have one type of comments, but I can see a future where that is not the case. We might have comments inside groups, on events, ... so it's probably best to keep that below the comment'able object.

> However if that is the case do we want to have another error report saying that the Comment isn't associated with the requested post or just reuse the permissions one?

Hm. I'd go with neither: actions on a comment that can't be found (either because the comment's GUID is wrong, or because the parents GUID is wrong) probably should just return a 404. Do you have any reasons against just throwing 404?

**Comment by HankG** [comment]
> Hm. I'd go with neither: actions on a comment that can't be found (either because the comment's GUID is wrong, or because the parents GUID is wrong) probably should just return a 404. Do you have any reasons against just throwing 404?

I don't have a reason against throwing a 404 (although I have it currently coded to throw a 403), it's more the descriptive comment that I was referring to.  In the current interim implementation I added a new error message of, "Comment is not associated with requested post" for this case.  If that works for everyone I can update the documentation to reflect this condition with a 404 error and change the code to throw 404 instead of 403.

**Comment by skyschub** [comment]
How about "Comment not found for the given post"? I don't really see a reason to tell an application "this comment exists, but somewhere else", I'd be fine with just returning a generic "this thing isn't here" error. Throwing a generic error would actually make querying simpler as well: you have to load the post anyway to check for permissions, and then you could just query "post.comments.find_by(guid: guid)" and see if there is something.

If we return a "this comment is here, but not at this post", you could actually query GUIDs from comments under private posts you don't see. Now, I don't have any actual privacy concerns for that, but since there is no way to get the comment anyway, I see no reason why a generic "not here" shouldn't do the job.

**Comment by HankG** [comment]
> How about "Comment not found for the given post"? 

Sounds good.  I'll tweak the language and the error code.
